// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// update_U_cpp
arma::mat update_U_cpp(arma::mat Z, arma::mat Omega, arma::mat Sigma, arma::mat eta, arma::mat Lambda, int n, int Q);
RcppExport SEXP _FMGPT_update_U_cpp(SEXP ZSEXP, SEXP OmegaSEXP, SEXP SigmaSEXP, SEXP etaSEXP, SEXP LambdaSEXP, SEXP nSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(update_U_cpp(Z, Omega, Sigma, eta, Lambda, n, Q));
    return rcpp_result_gen;
END_RCPP
}
// update_R_cpp
arma::vec update_R_cpp(arma::vec response_types, arma::mat Y, arma::mat eta, arma::mat Lambda, arma::mat U, int Q, int n, arma::vec r);
RcppExport SEXP _FMGPT_update_R_cpp(SEXP response_typesSEXP, SEXP YSEXP, SEXP etaSEXP, SEXP LambdaSEXP, SEXP USEXP, SEXP QSEXP, SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type response_types(response_typesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(update_R_cpp(response_types, Y, eta, Lambda, U, Q, n, r));
    return rcpp_result_gen;
END_RCPP
}
// update_eta_cpp2
Eigen::MatrixXd update_eta_cpp2(Eigen::MatrixXd Omega, Eigen::MatrixXd Lambda, Eigen::MatrixXd Z, int p, Eigen::MatrixXd U, Eigen::MatrixXd Sigma, Eigen::MatrixXd B, int n, Eigen::MatrixXd X, Eigen::MatrixXd rand_mat);
RcppExport SEXP _FMGPT_update_eta_cpp2(SEXP OmegaSEXP, SEXP LambdaSEXP, SEXP ZSEXP, SEXP pSEXP, SEXP USEXP, SEXP SigmaSEXP, SEXP BSEXP, SEXP nSEXP, SEXP XSEXP, SEXP rand_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type U(USEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type rand_mat(rand_matSEXP);
    rcpp_result_gen = Rcpp::wrap(update_eta_cpp2(Omega, Lambda, Z, p, U, Sigma, B, n, X, rand_mat));
    return rcpp_result_gen;
END_RCPP
}
// gamma_updateC2
Eigen::VectorXd gamma_updateC2(Eigen::MatrixXd X, Eigen::MatrixXd Y, Eigen::MatrixXd b, Rcpp::IntegerVector group, Rcpp::NumericVector pi1, Eigen::MatrixXd amat, Eigen::MatrixXd gmat, Eigen::MatrixXd omat, const Eigen::Map<Eigen::MatrixXd> Sigma, int ncolY, int ncolX);
RcppExport SEXP _FMGPT_gamma_updateC2(SEXP XSEXP, SEXP YSEXP, SEXP bSEXP, SEXP groupSEXP, SEXP pi1SEXP, SEXP amatSEXP, SEXP gmatSEXP, SEXP omatSEXP, SEXP SigmaSEXP, SEXP ncolYSEXP, SEXP ncolXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type b(bSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pi1(pi1SEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type amat(amatSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type gmat(gmatSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type omat(omatSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type ncolY(ncolYSEXP);
    Rcpp::traits::input_parameter< int >::type ncolX(ncolXSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_updateC2(X, Y, b, group, pi1, amat, gmat, omat, Sigma, ncolY, ncolX));
    return rcpp_result_gen;
END_RCPP
}
// omega_updateC2
Eigen::VectorXd omega_updateC2(Eigen::MatrixXd X, Eigen::MatrixXd Y, Eigen::MatrixXd b, Rcpp::IntegerVector group, double pi2, Eigen::MatrixXd amat, Eigen::MatrixXd gmat, Eigen::MatrixXd omat, const Eigen::Map<Eigen::MatrixXd> Sigma, int ncolY, int ncolX);
RcppExport SEXP _FMGPT_omega_updateC2(SEXP XSEXP, SEXP YSEXP, SEXP bSEXP, SEXP groupSEXP, SEXP pi2SEXP, SEXP amatSEXP, SEXP gmatSEXP, SEXP omatSEXP, SEXP SigmaSEXP, SEXP ncolYSEXP, SEXP ncolXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type b(bSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< double >::type pi2(pi2SEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type amat(amatSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type gmat(gmatSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type omat(omatSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type ncolY(ncolYSEXP);
    Rcpp::traits::input_parameter< int >::type ncolX(ncolXSEXP);
    rcpp_result_gen = Rcpp::wrap(omega_updateC2(X, Y, b, group, pi2, amat, gmat, omat, Sigma, ncolY, ncolX));
    return rcpp_result_gen;
END_RCPP
}
// eigenMatMult
SEXP eigenMatMult(Eigen::MatrixXd A, Eigen::MatrixXd B);
RcppExport SEXP _FMGPT_eigenMatMult(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenMatMult(A, B));
    return rcpp_result_gen;
END_RCPP
}
// eigenMapMatMult
SEXP eigenMapMatMult(const Eigen::Map<Eigen::MatrixXd> A, Eigen::Map<Eigen::MatrixXd> B);
RcppExport SEXP _FMGPT_eigenMapMatMult(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenMapMatMult(A, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FMGPT_update_U_cpp", (DL_FUNC) &_FMGPT_update_U_cpp, 7},
    {"_FMGPT_update_R_cpp", (DL_FUNC) &_FMGPT_update_R_cpp, 8},
    {"_FMGPT_update_eta_cpp2", (DL_FUNC) &_FMGPT_update_eta_cpp2, 10},
    {"_FMGPT_gamma_updateC2", (DL_FUNC) &_FMGPT_gamma_updateC2, 11},
    {"_FMGPT_omega_updateC2", (DL_FUNC) &_FMGPT_omega_updateC2, 11},
    {"_FMGPT_eigenMatMult", (DL_FUNC) &_FMGPT_eigenMatMult, 2},
    {"_FMGPT_eigenMapMatMult", (DL_FUNC) &_FMGPT_eigenMapMatMult, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_FMGPT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
