# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_U_cpp <- function(Z, Omega, Sigma, eta, Lambda, n, Q) {
    .Call(`_FMGPT_update_U_cpp`, Z, Omega, Sigma, eta, Lambda, n, Q)
}

update_R_cpp <- function(response_types, Y, eta, Lambda, U, Q, n, r) {
    .Call(`_FMGPT_update_R_cpp`, response_types, Y, eta, Lambda, U, Q, n, r)
}

update_eta_cpp2 <- function(Omega, Lambda, Z, p, U, Sigma, B, n, X, rand_mat) {
    .Call(`_FMGPT_update_eta_cpp2`, Omega, Lambda, Z, p, U, Sigma, B, n, X, rand_mat)
}

gamma_updateC2 <- function(X, Y, b, group, pi1, amat, gmat, omat, Sigma, ncolY, ncolX) {
    .Call(`_FMGPT_gamma_updateC2`, X, Y, b, group, pi1, amat, gmat, omat, Sigma, ncolY, ncolX)
}

omega_updateC2 <- function(X, Y, b, group, pi2, amat, gmat, omat, Sigma, ncolY, ncolX) {
    .Call(`_FMGPT_omega_updateC2`, X, Y, b, group, pi2, amat, gmat, omat, Sigma, ncolY, ncolX)
}

eigenMatMult <- function(A, B) {
    .Call(`_FMGPT_eigenMatMult`, A, B)
}

eigenMapMatMult <- function(A, B) {
    .Call(`_FMGPT_eigenMapMatMult`, A, B)
}

